### ISSUE TITLE
如何向内核传递要运行的命令

### ISSUE THREAD

**Issue by shzhxh** [Luchangcheng2333/zCore#10]
目前zCore上的CI测试依赖于CMDLINE参数向内核传递要运行的命令。
例如，内核启动后不进到shell而是直接执行`ps -a`则需要qemu-ops里包含`CMDLINE="ps?-a"`。
请问怎么向aarch64架构的zCore是如何传递这样的命令？

**Comment by shzhxh** [comment]
抱歉，更正一下。要向qemu传递的CMDLINE参数准确形式应该是这样的：

```
CMDLINE=LOG=error:ROOTPROC=/libc-test/src/functional/argv.exe
```
如果有参数的话用"?"来隔开。

**Comment by sunshine-lcc** [comment]
已经解决
