### ISSUE TITLE
运行程序的时候提示"unknown syscall: CLONE. exit..."

### ISSUE THREAD

**Issue by shzhxh** [Luchangcheng2333/zCore#6]
在qemu-system-aarch64上运行zCore，可以进到shell，但执行命令的时候(比如`ls`命令)，会出现提示`unknown syscall: CLONE. exit...`。

**Comment by sunshine-lcc** [comment]
这个问题正在解决中，目前按照通用的clone函数会出现指针跳转到异常地方的问题，下次commit会修复

**Comment by sunshine-lcc** [comment]
已解决该问题，没有刷新TLB导致
